// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArTbK7hFWdCETNw_KyuRuy0Nhhf39jxlg',
    appId: '1:43332741721:web:941a35a42f10c9ca3adf48',
    messagingSenderId: '43332741721',
    projectId: 'airlux-fc218',
    authDomain: 'airlux-fc218.firebaseapp.com',
    storageBucket: 'airlux-fc218.firebasestorage.app',
    measurementId: 'G-S32KR8VM16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArTbK7hFWdCETNw_KyuRuy0Nhhf39jxlg',
    appId: '1:43332741721:android:placeholder',
    messagingSenderId: '43332741721',
    projectId: 'airlux-fc218',
    authDomain: 'airlux-fc218.firebaseapp.com',
    storageBucket: 'airlux-fc218.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArTbK7hFWdCETNw_KyuRuy0Nhhf39jxlg',
    appId: '1:43332741721:ios:placeholder',
    messagingSenderId: '43332741721',
    projectId: 'airlux-fc218',
    authDomain: 'airlux-fc218.firebaseapp.com',
    storageBucket: 'airlux-fc218.firebasestorage.app',
    iosBundleId: 'com.example.airLux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArTbK7hFWdCETNw_KyuRuy0Nhhf39jxlg',
    appId: '1:43332741721:ios:placeholder',
    messagingSenderId: '43332741721',
    projectId: 'airlux-fc218',
    authDomain: 'airlux-fc218.firebaseapp.com',
    storageBucket: 'airlux-fc218.firebasestorage.app',
    iosBundleId: 'com.example.airLux',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArTbK7hFWdCETNw_KyuRuy0Nhhf39jxlg',
    appId: '1:43332741721:web:941a35a42f10c9ca3adf48',
    messagingSenderId: '43332741721',
    projectId: 'airlux-fc218',
    authDomain: 'airlux-fc218.firebaseapp.com',
    storageBucket: 'airlux-fc218.firebasestorage.app',
  );
}

